name: Test and Deploy
on:
  push:
    branches:
      - goshujin
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: "Setup"
        run: yarn install

      - name: "Test"
        run: |
          yarn tsc --noEmit
          yarn test

      - name: "Deploy"
        if: github.ref == 'refs/heads/main'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          yarn deploy
